# Generated by Django 4.1 on 2022-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NASBenchASRResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phenotype", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("index", models.CharField(db_index=True, max_length=64)),
                ("genotype", models.CharField(db_index=True, max_length=32)),
                ("test_per", models.JSONField(default=dict)),
                ("latency", models.JSONField(default=dict)),
                ("seed", models.IntegerField(default=0)),
                ("params", models.IntegerField(default=0)),
                ("flops", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
    ]
