# Generated by Django 4.1 on 2022-08-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NASHPOBench2Result",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("genotype", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("index", models.IntegerField(db_index=True)),
                ("phenotype", models.CharField(db_index=True, max_length=256)),
                ("batch_size", models.IntegerField(default=0)),
                ("lr", models.FloatField(default=0)),
                ("acc", models.FloatField(default=0)),
                ("cost", models.FloatField(default=0)),
            ],
            options={"abstract": False,},
        ),
    ]
