# Generated by Django 4.1 on 2022-08-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nashpobench2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nashpobench2result",
            name="genotype",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="nashpobench2result",
            name="phenotype",
            field=models.CharField(max_length=256),
        ),
    ]
