# Generated by Django 4.1 on 2022-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NASBenchMacroResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phenotype", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("index", models.IntegerField(db_index=True)),
                ("genotype", models.CharField(db_index=True, max_length=32)),
                ("test_acc", models.JSONField(default=dict)),
                ("mean_acc", models.FloatField(default=0)),
                ("std", models.FloatField(default=0)),
                ("params", models.IntegerField(default=0)),
                ("flops", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
    ]
