# Generated by Django 4.1 on 2022-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NASBenchGraphResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phenotype", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("index", models.IntegerField(db_index=True)),
                ("genotype", models.CharField(db_index=True, max_length=32)),
                ("valid_perf", models.JSONField(default=dict)),
                ("perf", models.JSONField(default=dict)),
                ("latency", models.JSONField(default=dict)),
                ("para", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
        ),
    ]
