# Generated by Django 4.1 on 2022-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nasbenchgraph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nasbenchgraphresult",
            name="para",
            field=models.JSONField(default=dict),
        ),
    ]
